// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtzb9xDHrWHvH8tdvM2AwQsGR1T6IqwFw',
    appId: '1:97758661684:web:634ac56cf887293588ce61',
    messagingSenderId: '97758661684',
    projectId: 'bob-hackathon-8a7ec',
    authDomain: 'bob-hackathon-8a7ec.firebaseapp.com',
    storageBucket: 'bob-hackathon-8a7ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwmW7WmlVOFd7G2PQLa_JZ_E4s-MrABQ',
    appId: '1:97758661684:android:a86e522c8fab59bd88ce61',
    messagingSenderId: '97758661684',
    projectId: 'bob-hackathon-8a7ec',
    storageBucket: 'bob-hackathon-8a7ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsCKrL2nfpQN4cORE_lGgEKW7CB9cLbY',
    appId: '1:97758661684:ios:4a02d37e337723e288ce61',
    messagingSenderId: '97758661684',
    projectId: 'bob-hackathon-8a7ec',
    storageBucket: 'bob-hackathon-8a7ec.appspot.com',
    iosClientId: '97758661684-ur16glrqlv9mj80m2v1fr59vj7brrmqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsCKrL2nfpQN4cORE_lGgEKW7CB9cLbY',
    appId: '1:97758661684:ios:4a02d37e337723e288ce61',
    messagingSenderId: '97758661684',
    projectId: 'bob-hackathon-8a7ec',
    storageBucket: 'bob-hackathon-8a7ec.appspot.com',
    iosClientId: '97758661684-ur16glrqlv9mj80m2v1fr59vj7brrmqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bob',
  );
}
